//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fligt
    {
        public int id { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> AirportID { get; set; }
        public Nullable<int> GateID { get; set; }
        public Nullable<int> RunwayID { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual Airport Airport { get; set; }
        public virtual City City { get; set; }
        public virtual Company Company { get; set; }
        public virtual Gate Gate { get; set; }
        public virtual Runway Runway { get; set; }
    }
}
